# Generated by Django 4.1.7 on 2023-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='un_campo',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=20),
        ),
    ]
